"""Initial

Revision ID: eb65f446d6b6
Revises: 87b62e1e787d
Create Date: 2020-09-13 11:16:34.766828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb65f446d6b6'
down_revision = '87b62e1e787d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
